#' Generate init
#'
#' This function is called by \code{\link{fit_escroc}} to
#' generate relevant initials values for the 3 Markov chains.
#'
#' @param mydata a list generated by \code{\link{prepare_data}}
#'
#' @return a list of lists of initial values for MCMC chains
#' @importFrom stats runif
#' @importFrom stats rnorm
#' @export
generate_init <- function(mydata) {
  lapply(1:3, function(chain) {
    delta <- delta_std <- rep(NA,mydata$nb_tracer)
    delta[mydata$id_prior_delta] <- mapply(function(mu,sd) rnorm(1,mu,sd),mydata$mu_prior_delta,mydata$sd_prior_delta)
    delta_std [!((1:mydata$nb_tracer) %in% mydata$id_prior_delta)] <- runif(mydata$nb_tracer-mydata$nb_prior_delta,.1,1)
    diet_short <- matrix(NA, mydata$nb_species, max(mydata$nb_prey_per_species))
    for (i in 1:(mydata$nb_species+2)) {
      if (mydata$nb_prey_per_species[i] > 1) {
        alpha <- runif(mydata$nb_prey_per_species[i])
        diet_short[i, 1:mydata$nb_prey_per_species[i]] <-
          alpha / sum(alpha)
      }
    }
    mean_signature_std <-
      matrix(NA, mydata$nb_species, mydata$nb_tracer)
    mean_signature_std[mydata$id_source_species,] <-
      runif(length(mydata$id_source_species) * mydata$nb_tracer,-3, 1)
    random_effect <-
      matrix(
        runif(mydata$nb_species * mydata$nb_tracer),
        mydata$nb_species,
        mydata$nb_tracer
      )
    random_effect[mydata$id_source_species,] <- NA
    signature_data <-
      matrix(NA,
             nrow(mydata$signature_data),
             ncol(mydata$signature_data))
    random_signature <-
      mydata$LOQ + matrix(runif(prod(dim(signature_data)),-10,-.1),
                   nrow(signature_data),
                   ncol(signature_data))
    signature_data[is.na(mydata$signature_data)] <-
      random_signature[is.na(mydata$signature_data)]
    list(
      mean_signature_std = mean_signature_std,
      random_effect = random_effect,
      signature_data = signature_data,
      diet_short = diet_short,
      delta = delta,
      delta_std =delta_std,
      .RNG.seed = chain,
      .RNG.name = c(
        "base::Super-Duper",
        "base::Wichmann-Hill",
        "base::Mersenne-Twister"
      )[chain]
    )
  })
}
